# Generated by Django 2.2.3 on 2019-07-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('reorder_level', models.IntegerField(verbose_name='reorder_level')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inventory', verbose_name='inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Reorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('status', models.CharField(max_length=10, verbose_name='status')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Inventory', verbose_name='inventoty')),
            ],
        ),
    ]
